

export const GET_STUDENTS = "GET_STUDENTS"
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS"
export const GET_STUDENTS_FAIL = "GET_STUDENTS_FAIL"

export const GET_RATES = "GET_RATES"
export const GET_RATES_SUCCESS = "GET_RATES_SUCCESS"
export const GET_RATES_FAIL = "GET_RATES_FAIL"

