export const GET_USERS = "GET_USERS"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

export const GET_MENTORS = "GET_MENTORS"
export const GET_MENTORS_SUCCESS = "GET_MENTORS_SUCCESS"
export const GET_MENTORS_FAIL = "GET_MENTORS_FAIL"

export const GET_PLATFORMS = "GET_PLATFORMS"
export const GET_PLATFORMS_SUCCESS = "GET_PLATFORMS_SUCCESS"
export const GET_PLATFORMS_FAIL = "GET_PLATFORMS_FAIL"

export const GET_PARTNERS = "GET_PARTNERS"
export const GET_PARTNERS_SUCCESS = "GET_PARTNERS_SUCCESS"
export const GET_PARTNERS_FAIL = "GET_PARTNERS_FAIL"

export const GET_ADVERTISINGS = "GET_ADVERTISINGS"
export const GET_ADVERTISINGS_SUCCESS = "GET_ADVERTISINGS_SUCCESS"
export const GET_ADVERTISINGS_FAIL = "GET_ADVERTISINGS_FAIL"

export const GET_ACTIVITES = "GET_ACTIVITES"
export const GET_ACTIVITES_SUCCESS = "GET_ACTIVITES_SUCCESS"
export const GET_ACTIVITES_FAIL = "GET_ACTIVITES_FAIL"

export const GET_PROJECTS = "GET_PROJECTS"
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS"
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL"

export const GET_STUDENTS = "GET_STUDENTS"
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS"
export const GET_STUDENTS_FAIL = "GET_STUDENTS_FAIL"

export const GET_RATES = "GET_RATES"
export const GET_RATES_SUCCESS = "GET_RATES_SUCCESS"
export const GET_RATES_FAIL = "GET_RATES_FAIL"

export const GET_QUESTIONS = "GET_QUESTIONS"
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS"
export const GET_QUESTIONS_FAIL = "GET_QUESTIONS_FAIL"

export const GET_ACTIVITY_TYPE = "GET_ACTIVITY_TYPE"
export const GET_ACTIVITY_TYPE_SUCCESS = "GET_ACTIVITY_TYPE_SUCCESS"
export const GET_ACTIVITY_TYPE_FAIL = "GET_ACTIVITY_TYPE_FAIL"

export const GET_FREELANCER = "GET_FREELANCER"
export const GET_FREELANCER_SUCCESS = "GET_FREELANCER_SUCCESS"
export const GET_FREELANCER_FAIL = "GET_FREELANCER_FAIL"

export const GET_CONTACTS = "GET_CONTACTS"
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS"
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL"

export const GET_ABOUTUS = "GET_ABOUTUS"
export const GET_ABOUTUS_SUCCESS = "GET_ABOUTUS_SUCCESS"
export const GET_ABOUTUS_FAIL = "GET_ABOUTUS_FAIL"
