export const GET_USERS = "GET_USERS"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

export const GET_MENTORS = "GET_MENTORS"
export const GET_MENTORS_SUCCESS = "GET_MENTORS_SUCCESS"
export const GET_MENTORS_FAIL = "GET_MENTORS_FAIL"

export const GET_PROJECTS = "GET_PROJECTS"
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS"
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL"

export const GET_STUDENTS = "GET_STUDENTS"
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS"
export const GET_STUDENTS_FAIL = "GET_STUDENTS_FAIL"

export const GET_RATES = "GET_RATES"
export const GET_RATES_SUCCESS = "GET_RATES_SUCCESS"
export const GET_RATES_FAIL = "GET_RATES_FAIL"

export const GET_FREELANCER = "GET_FREELANCER"
export const GET_FREELANCER_SUCCESS = "GET_FREELANCER_SUCCESS"
export const GET_FREELANCER_FAIL = "GET_FREELANCER_FAIL"