export const GET_ABOUTUS = "GET_ABOUTUS"
export const GET_ABOUTUS_SUCCESS = "GET_ABOUTUS_SUCCESS"
export const GET_ABOUTUS_FAIL = "GET_ABOUTUS_FAIL"

export const ADD_ABOUTUS = "ADD_ABOUTUS"
export const ADD_ABOUTUS_SUCCESS = "ADD_ABOUTUS_SUCCESS"
export const ADD_ABOUTUS_FAIL = "ADD_ABOUTUS_FAIL"

export const UPDATE_MENTOR = "UPDATE_MENTOR"
export const UPDATE_MENTOR_SUCCESS = "UPDATE_MENTOR_SUCCESS"
export const UPDATE_MENTOR_FAIL = "UPDATE_MENTOR_FAIL"

export const DELETE_MENTOR = "DELETE_MENTOR"
export const DELETE_MENTOR_SUCCESS = "DELETE_MENTOR_SUCCESS"
export const DELETE_MENTOR_FAIL = "DELETE_MENTOR_FAIL"
