export const GET_LANDING_PAGE_CONTENT = "GET_LANDING_PAGE_CONTENT"
export const GET_LANDING_PAGE_CONTENT_SUCCESS =
  "GET_LANDING_PAGE_CONTENT_SUCCESS"
export const GET_LANDING_PAGE_CONTENT_FAIL = "GET_LANDING_PAGE_CONTENT_FAIL"

export const ADD_LANDING_PAGE_SECTION = "ADD_LANDING_PAGE_SECTION"
export const ADD_LANDING_PAGE_SECTION_SUCCESS =
  "ADD_LANDING_PAGE_SECTION_SUCCESS"
export const ADD_LANDING_PAGE_SECTION_FAIL = "ADD_LANDING_PAGE_SECTION_FAIL"

export const UPDATE_MENTOR = "UPDATE_MENTOR"
export const UPDATE_MENTOR_SUCCESS = "UPDATE_MENTOR_SUCCESS"
export const UPDATE_MENTOR_FAIL = "UPDATE_MENTOR_FAIL"

export const DELETE_MENTOR = "DELETE_MENTOR"
export const DELETE_MENTOR_SUCCESS = "DELETE_MENTOR_SUCCESS"
export const DELETE_MENTOR_FAIL = "DELETE_MENTOR_FAIL"
