/* doctors */
export const GET_DOCTORS = "GET_DOCTORS"
export const GET_DOCTORS_SUCCESS = "GET_DOCTORS_SUCCESS"
export const GET_DOCTORS_FAIL = "GET_DOCTORS_FAIL"

// Offers
export const GET_OFFERS = "GET_OFFERS"
export const GET_OFFERS_SUCCESS = "GET_OFFERS_SUCCESS"
export const GET_OFFERS_FAIL = "GET_OFFERS_FAIL"

// clinics
export const GET_CLINICS = "GET_CLINICS"
export const GET_CLINICS_SUCCESS = "GET_CLINICS_SUCCESS"
export const GET_CLINICS_FAIL = "GET_CLINICS_FAIL"

// pages
export const GET_PAGES= "GET_PAGES"
export const GET_PAGES_SUCCESS = "GET_PAGES_SUCCESS"
export const GET_PAGES_FAIL = "GET_PAGES_FAIL"

// contact
export const GET_CONTACT = "GET_CONTACT"
export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS"
export const GET_CONTACT_FAIL = "GET_CONTACT_FAIL"

// CONSULTATION
export const GET_CONSULTATIONS = "GET_CONSULTATIONS"
export const GET_CONSULTATIONS_SUCCESS = "GET_CONSULTATIONS_SUCCESS"
export const GET_CONSULTATIONS_FAIL = "GET_CONSULTATION_FAIL"

// BOOKING
export const GET_BOOKING = "GET_BOOKING"
export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS"
export const GET_BOOKING_FAIL = "GET_BOOKING_FAIL"

// FILES
export const GET_FILES = "GET_FILES"
export const GET_FILES_SUCCESS = "GET_FILES_SUCCESS"
export const GET_FILES_FAIL = "GET_FILES_FAIL"


/* ORDERS */
export const GET_ORDERS_DATA = "GET_ORDERS_DATA"
export const GET_ORDERS_DATA_SUCCESS = "GET_ORDERS_DATA_SUCCESS"
export const GET_ORDERS_DATA_FAIL = "GET_ORDERS_DATA_FAIL"